services:
  - type: web
    name: simpledocs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      daphne -b 0.0.0.0 -p 10000 onlinedocs.asgi:application

  - type: worker
    name: simpledocs-celery
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A onlinedocs worker --loglevel=info
