services:
  - type: web
    name: simpledocs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p 10000 onlinedocs.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: onlinedocs.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        value: <your database url>
      - key: REDIS_URL
        value: <your redis url>
      - key: DJANGO_SECRET_KEY
        value: <your secret key>
